export const ROUTES = {
  HOME:           '/',
  ABOUT:          '/about',
  EVENTS:         '/events',
  SERVICES:       '/services',
  FRAMEWORK:      '/framework',
  RESOURCES:      '/resources',
  CERTIFICATION:  '/certification',
  COMMUNITY:      '/community',
  NEWS:           '/news',
  MEDIA_HUB:      '/media-hub',
  CONTACT:        '/contact',
  MEMBERSHIP:     '/membership',
  NOMINEES:       '/nominees',
  WINNERS:        '/winners',
  PRODUCT_REVIEWS:'/services/esg-solutions',
  LOGIN:          '/login',
  REGISTER:       '/register',
  PROFILE:        '/profile',
  DASHBOARD:      '/user/dashboard',
  WORKSHOPS:      '/expert-workshops',
  NOTIFICATIONS:  '/notifications',
  PRIVACY:        '/privacy',
  ADMIN:          '/admin-dashboard',
  ADMIN_USERS:    '/admin-dashboard/users',
  ADMIN_NOMINEES: '/admin-dashboard/nominees',
} as const;
